image: lorisleiva/laravel-docker:latest

deploy-testing:
  stage: deploy
  script:
    - ssh $SERVER_TOKEN_TEST -t "cd ${WEB_ROOT} && git pull && sh deploy.sh"
  environment:
    name: test
    url: http://domaintest.f1good.com
  only:
    - develop
  tags:
    - domain
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod -R 600 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

deploy-master:
  stage: deploy
  script:
    - ssh $SERVER_TOKEN -t "cd ${WEB_ROOT} && git pull && sh deploy.sh"
  environment:
    name: test
    url: http://domain.f1good.com
  only:
    - master
  tags:
    - domain
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod -R 600 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts